version: "3.7"
services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: root
      MYSQL_DATABASE: kubermarket

  springboot:
    depends_on:
      - docker-mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/kubermarket?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
      #MYSQL_ADDRESS: mysql
      #MYSQL_PORT: 13306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8080:8080
    restart: always
#networks:
#  my-network:
#    driver: bridge

